---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    GITHUB_TOKEN: AgATc+e56Kb2ybqbO43d0N/qDSyoEVlZUnvuTZQSo2kJlmrbIhUJ/iyubQv/1oiw9KzsJqpTgAxNPD0pP0YPzcYy+7H6T/BIWF1ZemvYbapFGqd56vZAvW1sS3AiehQhfd18BlwNCgywtvO/Ucl7Nq8wLTtrAxFmI1EBbhzguH/Vy1NaZHaYWHcAEtmSvAIqXoh7Vew3fUzVe3NXERvp3QUKekxGBgpBtvDqvTkbqNWoZJFvxgr2x+Whz4BV1B5iobjjcg++mgKzJvTE9Msoqmme7KCVD0/gGtLWIjJHbyYVLlfx0O+o/EHLr8cGEA09Ypc+KVKEEcOdYK0ty1fnSzou0+cAahcXBfAtiMD6hV9VwcTdqFoq4erBriFnh5fG7TpHPGWyBbmExdIvcMX3xT+CxEsbOZGQdA5TXuCF6Q6QdACK+QqTeGJTTbXA6QSnpLs0jMoZFZQV184I/1idOQykywhoi/cgUHsLuOuOVUDKtME7HCdZInLj8diLzNhDiJzq7Tr2xDZMPLWHCd4w0e9ABcHkQjjaCkuwNHqfTeBgccpZGBqT+fLVuSrAjSqzJSdqHoM32ebHdmx5UVaUPBY7fORB3RH6MA6y6OujQ7Vbi7aI/3dquo+uwCgnGJWLUYzhV7TZQAtpLAlYlKhBvEMNgqE5eN4qh5EoDNeBYGiibKtBmg0wzFMo+VtpJ5HkicR+D/iVTkVnNhcxPmEGlzMzy33Cc6n9lTp0CDVi3VxmBTOAbnQHfC2YWQ==
  template:
    metadata:
      creationTimestamp: null
      name: backstage-secrets
      namespace: backstage
    type: Opaque
