---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBBI5AFkijZ2Khz39IXmx6VtbvdArnhynAy8I2hqGxjQ652jQWYULVKGDe6W/4zhD6ZbzM4FccKbbtR4ZyV0p/DJUaPDk1loUJgLu5I7lIwDeT/eJsqCQNchyeIteK4yFcpj4f7xFnrimKjTBOfXs2AM5nLoMTbC1RLe+xwHomcLQztdQ4Al9h9NSwnB6v5zfHjiJWCvmRElYg9o1eBxud+W9A03w7FrE8nMN8w3r+O9cK00ihY8jY/ELKbDVQUiURnwCbYxMts8nUZ1oqRN+57I/z2PXJaskR9pYdJBNQQ/sfKYQYmtyOMa05ZlYzeNN2kfSlGRaQpGq9oK6sSIefzI6QSZpjczfxmXj90cWPx6HD1ucjf37eWJsviJcfBXO0FejaVAgQbYXTwy4Q6gIcbOF3VaKYwYwJGxKmm2e4noUIZNvXbNVWo72gR1Dfu6NQCyG+Lo9hM/fQHXnfCGxD84jqx4xF/xkQT49CFA/rQgLf9ImhE9W1b8U68ZpCSYYM6nMugbCaVuy/L0Yey/vAVosOhnPolhmoS1g+kqGksIjvt+H6kKFG8Q2fbtKbXAwhA+drRdSj0RFCX5BD7lvQNwY9ctGncuOyhb+TtKKnJW7M48eqNOeJl17fF2WhhcK3Ea7CbYNaxKLIVWre+AHn4CU38Hal6VqqD2Ywhuj7AAEthrYDY1vOqV9w6eXoge4XxU02V99KLZKCE
    POSTGRES_USER: AgBp42WaNA/mJ94ZurT0x6OZu1bPf37JvR/kcW3s8lnW+J+3e0YClv7gtUyOqZqP7YtHLAn3fJLFJ2PNtldeL14JHy9W80+58BOv5NrgB6ji1+mPrnFp+ZdDs03hXGzpdgDOYSz4PXIJFfdkNDZ8quFuhh9c2wp5dM0Qrqeefz3NovHHnw9MrQRIjwaAsRVQb9oT0jQY+XiG1wuQAr1v0ZBVs/FtoZGO8VBJ+oyUBYvDYvffOM8HiMMhP0Rm9rgkKByDllYXaIxP8XtWb/8QUu6E0a9kRfaz/rgeMvmhZIM+m207bW3qxiw+1LK9fty6CXYJB44d6CH5T4HM5sYbleguSZ8G38AwDI2jDzSn9gzmrQaZ70CvgJ5DMEyGuLb/MZVwaFhbxoO2/1JpJVkK/pjwJ1fnMRnH3xPb0DfHhMypbCYu8T9kGzJAIg842LWjYQYRFeaRaOROb5yK1gXhsyyXggF1lGPYf43ug6eZbt5W63yiSv2GlgXHps2Qiu2aZQC2o4Ffzsr6sUitUAPLcWh78WfvKt9TpCu+gHqvIdKLFwhoJWNk2dVTwtjMxOn+Q6+4m7YQLK7cZV+fs0OUhqZHynWV1Xg9YZuhHp+XN+7YGBaM1yC5Ifyj6A51oBmTrTmlCrssSzbYiU1voyL++RQqf4mAV6QsM+2bh3TIGl0VZelWorUfWuxK7U3DUP1SWjfID+ereNFVFw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgres
    type: Opaque
