replicaCount: 1

image:
  repository: backstage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7007

# ingress:
#   enabled: false
#   annotations: {}
#   hosts:
#     - host: backstage.example.com
#       paths:
#         - path: /
#           pathType: Prefix
#   tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  APP_CONFIG_backend_baseUrl: "http://backstage.example.com"
  APP_CONFIG_backend_cors_origin: "http://backstage.example.com"
  DATABASE_URL: "postgresql://user:password@postgres:5432/backstage"

postgres:
  enabled: true
  postgresqlUsername: backstage
  postgresqlPassword: backstagepassword
  postgresqlDatabase: backstage

nodeSelector: {}

tolerations: []

affinity: {}
